(function(window,document){
  let toastTimer,previousFocus=null;
  function mostrarToast(texto){const toast=document.querySelector("#toast");if(!toast)return;toast.textContent=texto;toast.classList.add("visivel");window.clearTimeout(toastTimer);toastTimer=window.setTimeout(function(){toast.classList.remove("visivel");},3200);}
  function focaveis(modal){return Array.from(modal.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')); }
  function abrirModal(opener){const modal=document.querySelector("#modal-contribuir");if(!modal)return;previousFocus=opener||document.activeElement;modal.classList.add("aberto");modal.setAttribute("aria-hidden","false");const close=document.querySelector("#modal-close");if(close)close.focus();}
  function fecharModal(){const modal=document.querySelector("#modal-contribuir");if(!modal)return;modal.classList.remove("aberto");modal.setAttribute("aria-hidden","true");if(previousFocus&&typeof previousFocus.focus==="function")previousFocus.focus();previousFocus=null;}
  function configurarMenu(){const toggle=document.querySelector("#menu-toggle");const nav=document.querySelector(".cabecalho nav");if(!toggle||!nav||toggle.dataset.bound==="true")return;toggle.dataset.bound="true";toggle.addEventListener("click",function(){const aberto=nav.classList.toggle("aberto");toggle.setAttribute("aria-expanded",String(aberto));toggle.setAttribute("aria-label",aberto?"Fechar menu":"Abrir menu");});}
  function inicializarUI(){configurarMenu();document.addEventListener("click",function(event){const opener=event.target.closest("[data-open-modal]");if(opener){abrirModal(opener);return;}const closer=event.target.closest("#modal-close");if(closer){fecharModal();return;}const toastButton=event.target.closest("[data-toast]");if(toastButton){mostrarToast(toastButton.getAttribute("data-toast"));return;}const modal=document.querySelector("#modal-contribuir");if(modal&&event.target===modal)fecharModal();});document.addEventListener("keydown",function(event){const modal=document.querySelector("#modal-contribuir");if(event.key==="Escape"&&modal?.classList.contains("aberto")){event.preventDefault();fecharModal();return;}if(event.key==="Tab"&&modal?.classList.contains("aberto")){const f=focaveis(modal);if(!f.length)return;const first=f[0],last=f[f.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});}
  window.PontoDignoUI={mostrarToast,abrirModal,fecharModal,inicializarUI};
})(window,document);